export const GAME_ACTIONS = {
  STARTED: 'STARTED',
  DONE: 'DONE',
  SET_TIME: 'SET_TIME',
  SET_BREED: 'SET_BREED',
  SET_BREEDS: 'SET_BREEDS',
  SET_LIKED: 'SET_LIKED',
  SET_DISLIKED: 'SET_DISLIKED',
  SET_SKIPPED: 'SET_SKIPPED',
};
